net = slim.dropout(net, dropout_keep_prob, is_training=is_training, scope='dropout7')

net0 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_0')
net1 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_1')
net2 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_2')
net3 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_3')
net4 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_4')
net5 = slim.conv2d(net, num_classes, [1, 1],
                   activation_fn=None,
                   normalizer_fn=None,
                   biases_initializer=tf.zeros_initializer(),
                   scope='fc8_5')